#Defines or set active application profile: live or development
spring.profiles.active: test

---
spring:
  profiles: test
  application.name: BsfTest
#  datasource:
#    url: jdbc:h2:mem:bsf_db
#    username: user
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2.console.enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/bsf_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&noAccessToProcedureBodies=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.show_sql: false
    properties.hibernate.use_sql_comments: true
    properties.hibernate.format_sql: true
    properties.hibernate.type: trace
    hibernate.ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/bsf
          jwk-set-uri: http://localhost:8083/auth/realms/bsf/protocol/openid-connect/certs

rest.security:
  enabled: true
  issuer-uri: http://localhost:8083/auth/realms/bsf
  api-matcher: '/api/bsf/**'
  cors.allowed-origins: '*'
  cors.allowed-headers: '*'
  cors.allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  cors.max-age: 3600

logging:
  file: logs/application.log
  file.max-size: 200MB
  level:
    org.apache.http: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.web: INFO
    com.bsf.resource: INFO
    org.springframework.security: INFO
    org.keycloak: TRACE

server:
  port: 8081
#  servlet:
#    context-path: /api/bsf/

userAuthorizationUri: http://localhost:8083/auth/realms/bsf/protocol/openid-connect/token
resourceServer: http://localhost:8081/api/bsf/
adminClientId: newClient
adminClientSecret: newClientSecret